### ISSUE TITLE
Allow Custom Redis Configuration

### ISSUE THREAD

**Issue by Kkoile** [cap-js-community/event-queue#161]
In our logging system we see recurring logs that redis socket close unexpectedly, which is related to event-queue:
![image](https://github.com/cap-js-community/event-queue/assets/8350530/3b75a787-f992-4fbb-8c4b-2d71f851efc5)
Based on the following github issue this could be resolved by setting a `pingInterval`: https://github.com/redis/node-redis/issues/2058

It would be great if you could provide a way to pass custom redis configuration when connecting, so that we can set `pingInterval` in our application.

**Comment by soccermax** [comment]
W'll add this with the next release - tmr or the day after tmr
