### ISSUE TITLE
Conflict with @cap-js/telemetry

### ISSUE THREAD

**Issue by corporateuser** [cap-js-community/event-queue#165]
Hello, in https://github.com/cap-js-community/event-queue/blob/main/src/runner/runner.js#L142
you're creating a context which looks like an http context, but actually is not.
This causes [@cap-js/telemetry](https://github.com/cap-js/telemetry/blob/main/lib/tracing/trace.js#L94) to throw as it expects that context having "http" property to be a correct http request, but it is not.
Maybe event-queue should not pretend its requests are http requests?

I've created an [issue in telemetry repo](https://github.com/cap-js/telemetry/issues/129) as well, as I'm not sure who actually should fix this. Maybe you could have internal conversation on this?

**Comment by sjvans** [comment]
hi @soccermax 

where is `getSubdomain()` needed in/ for logging?

best,
sebastian

**Comment by soccermax** [comment]
@sjvans, we use this method for extracting the subdomain, as it was the most commonly used method with CDS and xssec. Is there a better approach where we can store this information? We would like to have the subdomain available even when we are not running in the context of an HTTP request (event-queue). For tenant we have `context.tenant` but would we do this for subdomain?

**Comment by sjvans** [comment]
hi @soccermax 

for `@sap/xssec`-based authentication, we offer [`req.user.tokenInfo`](https://cap.cloud.sap/docs/node.js/authentication#user-token-info) (since one of the last couple of releases). let me know if that isn't sufficient for you.

best,
sebastian

**Comment by soccermax** [comment]
@sjvans thanks I'll look into it.
@corporateuser I'll release a new version with a fix. Thanks for reporting

**Comment by soccermax** [comment]
release is in the build process: https://github.com/cap-js-community/event-queue/releases/tag/v1.4.1
