### ISSUE TITLE
CDS does not expose authInfo on req.user.authInfo

### ISSUE THREAD

**Issue by oklemenz2** [cap-js-community/event-queue#183]
Currently only the tokenInfo is exposed at `req.user.tokenInfo`.
The implementation shall be aligned with CDS standards.

**Comment by soccermax** [comment]
still ongoing discussion with CDS if we can align to that CDS also offers `authInfo` on `req.user`. If we can agree on this we can close this issue

**Comment by Markus-Schroeder-de** [comment]
Hello everyone. I also suspect that there is a problem. I am currently working on a project where I briefly checked and output req.user many weeks ago and everything looked as expected. Yesterday I continued to work on the topic and am surprised that req.user is now empty, but I can find the expected information in req.res.user. I am a bit confused at the moment, but perhaps this information will help.

**Comment by soccermax** [comment]
@Markus-Schroeder-de Could you please specify the context in which you encountered this? Was it within the execution of the event queue, or did you use a CAP Entity Handler invoked by an HTTP request? Additionally, could you share which version of CAP you are using?

**Comment by Markus-Schroeder-de** [comment]
i use a cap entity-handler for an http request. Auth is with XSUAA. i have added a function userinfo() in the Service. 
![image](https://github.com/cap-js-community/event-queue/assets/135587617/eeccb649-172a-4f10-90d6-99f142ea9fa6)
user in req is empty... 
![image](https://github.com/cap-js-community/event-queue/assets/135587617/91c138b8-0287-44dd-9610-057075a7dd77)
but (instead) user in req.res. is there: 
![image](https://github.com/cap-js-community/event-queue/assets/135587617/3bfdbc70-cb7e-4fd4-a77e-6dcd6fa712d0)
I wanted to start implementing the event mesh (and Authorization (not authentication) at the same time) today and the same function was still outputting the User object for a few weeks ago. In the meantime, dependency updates were made, but nothing fundamental changed. And I'm just fumbling around in the fog as to why it is the way it is.

**Comment by Markus-Schroeder-de** [comment]
forgot the versions: ├── @cap-js/cds-typer@0.23.0
├── @cap-js/sqlite@1.7.3
├── @repo-tooling/eslint-plugin-dprint@0.0.4
├── @rushstack/node-core-library@5.4.1
├── @sap-cloud-sdk/connectivity@3.16.0
├── @sap-cloud-sdk/http-client@3.16.0
├── @sap-cloud-sdk/resilience@3.16.0
├── @sap/approuter@16.6.0
├── @sap/cds-dk@7.9.4
├── @sap/cds@7.9.3
├── @sap/hana-client@2.21.28
├── @sap/xsenv@5.1.0
├── @sap/xssec@4.1.3
├── @sapui5/types@1.120.12
├── @types/uuid@10.0.0
├── @typescript-eslint/eslint-plugin@7.16.0
├── @typescript-eslint/parser@7.16.0
├── @ui5/cli@3.11.0
├─┬ approuter@ -> ./app/router
│ └── @sap/approuter@16.6.0 deduped
├── cds-plugin-ui5@0.9.3
├── cds-swagger-ui-express@0.8.0
├── cf-nodejs-logging-support@7.3.0
├─┬ ch.ktzh.bi.vsa.sjw.admin@1.0.0 -> ./app/ch.ktzh.bi.vsa.sjw.admin
│ ├── ch.ktzh.bi.vsa.sjw.library@1.0.0 deduped -> ./app/ch.ktzh.bi.vsa.sjw.library
│ ├── ui5-middleware-cap@3.2.11 deduped
│ ├── ui5-tooling-modules@3.7.0 deduped
│ └── ui5-tooling-transpile@3.4.5 deduped
├─┬ ch.ktzh.bi.vsa.sjw.assignments@1.0.0 -> ./app/ch.ktzh.bi.vsa.sjw.assignments
│ ├── ch.ktzh.bi.vsa.sjw.library@1.0.0 deduped -> ./app/ch.ktzh.bi.vsa.sjw.library
│ ├── ui5-middleware-cap@3.2.11 deduped
│ ├── ui5-tooling-modules@3.7.0 deduped
│ └── ui5-tooling-transpile@3.4.5 deduped
├─┬ ch.ktzh.bi.vsa.sjw.communities@1.0.0 -> ./app/ch.ktzh.bi.vsa.sjw.communities
│ ├── ch.ktzh.bi.vsa.sjw.library@1.0.0 deduped -> ./app/ch.ktzh.bi.vsa.sjw.library
│ ├── ui5-middleware-cap@3.2.11 deduped
│ ├── ui5-tooling-modules@3.7.0 deduped
│ └── ui5-tooling-transpile@3.4.5 deduped
├─┬ ch.ktzh.bi.vsa.sjw.launchpad@1.0.0 -> ./app/ch.ktzh.bi.vsa.sjw.launchpad
│ ├── ch.ktzh.bi.vsa.sjw.library@1.0.0 deduped -> ./app/ch.ktzh.bi.vsa.sjw.library
│ ├── ui5-middleware-cap@3.2.11 deduped
│ ├── ui5-tooling-modules@3.7.0 deduped
│ └── ui5-tooling-transpile@3.4.5 deduped
├─┬ ch.ktzh.bi.vsa.sjw.library@1.0.0 -> ./app/ch.ktzh.bi.vsa.sjw.library
│ ├── @ui5/ts-interface-generator@0.8.3
│ ├── ui5-tooling-modules@3.7.0 deduped
│ └── ui5-tooling-transpile@3.4.5 deduped
├─┬ ch.ktzh.bi.vsa.sjw.schoolbuildings@1.0.0 -> ./app/ch.ktzh.bi.vsa.sjw.schoolBuildings
│ ├── ch.ktzh.bi.vsa.sjw.library@1.0.0 deduped -> ./app/ch.ktzh.bi.vsa.sjw.library
│ ├── ui5-middleware-cap@3.2.11 deduped
│ ├── ui5-tooling-modules@3.7.0 deduped
│ └── ui5-tooling-transpile@3.4.5 deduped
├─┬ ch.ktzh.bi.vsa.sjw.schoolunits@1.0.0 -> ./app/ch.ktzh.bi.vsa.sjw.schoolunits
│ ├── ch.ktzh.bi.vsa.sjw.library@1.0.0 deduped -> ./app/ch.ktzh.bi.vsa.sjw.library
│ ├── ui5-middleware-cap@3.2.11 deduped
│ ├── ui5-tooling-modules@3.7.0 deduped
│ └── ui5-tooling-transpile@3.4.5 deduped
├─┬ ch.ktzh.bi.vsa.sjw.teachingstaff@1.0.0 -> ./app/ch.ktzh.bi.vsa.sjw.teachingstaff
│ ├── ch.ktzh.bi.vsa.sjw.library@1.0.0 deduped -> ./app/ch.ktzh.bi.vsa.sjw.library
│ ├── ui5-middleware-cap@3.2.11 deduped
│ ├── ui5-tooling-modules@3.7.0 deduped
│ └── ui5-tooling-transpile@3.4.5 deduped
├── dotenv@16.4.5
├── eslint-import-resolver-typescript@3.6.1
├── eslint-plugin-codegen@0.28.0
├── eslint-plugin-import@2.29.1
├── eslint-plugin-simple-import-sort@12.1.1
├── eslint-plugin-sort-destructure-keys@2.0.0
├── eslint@8.57.0
├── husky@9.0.11
├── npm-run-all@4.1.5
├── nx@19.4.2
├── passport@0.7.0
├── properties-reader@2.3.0
├── rimraf@6.0.0
├── sqlite3@5.1.7
├── ts-loader@9.5.1
├── ts-node@10.9.2
├── tsconfig-paths@4.2.0
├── typescript@5.5.3
├── ui5-middleware-cap@3.2.11
├── ui5-tooling-modules@3.7.0
├── ui5-tooling-transpile@3.4.5
├── uuid@10.0.0
└── zip-a-folder@3.1.7

**Comment by soccermax** [comment]
@Markus-Schroeder-de IMO your issue is that the user is still there but the properties are not enumerable. So `console.log` won't print them but you can access them e.g. with `req.user.id`.
You know that the event-queue and event mesh are very different things, right? Or do you plan to use both in combination?

**Comment by Markus-Schroeder-de** [comment]
> You know that the event-queue and event mesh are very different things, right?

I have already done a few BTP projects, but so far always nestjs, this is my first pure CAP project and yes, I'm still struggling with it and now that you mention it, I realize that my colleagues (who were at the recap) sent me down the wrong track. But what I would certainly have noticed soon (if I didn't do too much at the same time) is that after updating the node version and the dependencies, not everything (e.g. cds-ts watch and the mentioned req.user) no longer works as expected. Thanks for your prompt replies.

**Comment by oklemenz2** [comment]
Subdomain shall be derived from tokenInfo... `req.user.tokenInfo.extAttributes?.zdn`
