### ISSUE TITLE
configValue is checked falsy, thus e.g. option value `false` is never applied

### ISSUE THREAD

**Issue by oklemenz2** [cap-js-community/event-queue#245]
https://github.com/cap-js-community/event-queue/blob/f595de169b5eb0fbd3b1c6bc74096d511cb3af9a/src/initialize.js#L172C26-L172C37

**Comment by soccermax** [comment]
```js

configValue ?? cds.env.eventQueue?.[configName] ?? defaultValue

```

`??` checks for undefined/null. So it should not check for falsy? Or what do you think?

**Comment by oklemenz** [comment]
Right, that's true
