### ISSUE TITLE
Silent drop of Redis when connection fails 

### ISSUE THREAD

**Issue by mvoros** [cap-js-community/event-queue#246]
When there is an issue with connection to Redis, the redis option gets disabled but there is no error/warning message that this happened. In Initialized.js, there is the following code

```
  if (redisEnabled) {
    config.redisEnabled = await redis.connectionCheck(config.redisOptions);
  }
```
IMO it would be good to raise an error message that redis is being disabled due to failed connection check. One of the reasons why it fails silently is that error handles for redis client are registered too late in the function createClientAndConnect.

```
const createClientAndConnect = async (options, errorHandlerCreateClient) => {
  try {
    const client = _createClientBase(options);
    await client.connect();  <=== Already fails here before handlers are registered
    client.on("error", (err) => {
      const dateNow = Date.now();
      if (dateNow - lastErrorLog > LOG_AFTER_SEC * 1000) {
        cds.log(COMPONENT_NAME).error("error from redis client for pub/sub failed", err);
        lastErrorLog = dateNow;
      }
    });

    client.on("reconnecting", () => {
      const dateNow = Date.now();
      if (dateNow - lastErrorLog > LOG_AFTER_SEC * 1000) {
        cds.log(COMPONENT_NAME).info("redis client trying reconnect...");
        lastErrorLog = dateNow;
      }
    });
    //HERE WE SHOULD CALL client.connect
    return client;
  } catch (err) {
    errorHandlerCreateClient(err);
  }
};
```
When the order is change, cds serve does not start as it keeps try to establish redis connection first. 

I think at bare minimum it should raise an error message that it's turning off redis due to failed connection. But IMO it would better to not start the service when Redis is not accessible but configured.

**Comment by soccermax** [comment]
I agree with the logging and I'll improve this in the next release.
For the part of killing the server in case of redis is not available I'm not so sure. In case of local development where the backend is started with CDS_ENV=production and no redis is available this would always prevent the server from starting.
I could introduce a flag that could be enabled like: `crashOnRedisNotAvailable` - would that work for you?

**Comment by mvoros** [comment]
I am actually not worried too much about development. There it's not a big problem if Redis is not used for messaging. I am more worried about production. I think that CAP should not start when Redis is not available during start (only during start). The problem is that it will not try to re-connect later, it will simply disable it completely. If connection fails later, it's OK to fail as the app should handle this scenario.

**Comment by mvoros** [comment]
That's fine. Thanks

**Comment by soccermax** [comment]
new version is released: https://github.com/cap-js-community/event-queue/releases/tag/v1.7.3
name of the parameter is `crashOnRedisUnavailable`

**Comment by mvoros** [comment]
This works. Thanks
