### ISSUE TITLE
runInterval limitations

### ISSUE THREAD

**Issue by mvoros** [cap-js-community/event-queue#256]
Hi,

I am doing some load testing for the application that generates large number of events that are supposed to be processed asynchronously. The setup is to use a single tenant Redis as a backend. 

The problem is that the runners seem to not run often enough to process the events in the queue. Hence I decided to reduce runInterval to 1000ms. I got an error that it must be more than 10 seconds. Hence I changed it to 10 001 ms. This went through but no events have been processed anymore. I traced it down to this code in runner.js

```
const _executeEventsAllTenantsRedis = async (tenantIds) => {
  const logger = cds.log(COMPONENT_NAME);
  try {
    // NOTE: do checks for all tenants on the same app instance --> acquire lock tenant independent
    //       distribute from this instance to all others
    const dummyContext = new cds.EventContext({});
    const couldAcquireLock = await trace(
      dummyContext,
      "acquire-lock-master-runner",
      async () => {
        return await distributedLock.acquireLock(dummyContext, EVENT_QUEUE_RUN_REDIS_CHECK, {
          expiryTime: eventQueueConfig.runInterval * 0.95,
          tenantScoped: false,
        });
      },
      { newRootSpan: true }
    );
    if (!couldAcquireLock) {
      return;
    }
```
The problem is with the statement eventQueueConfig.runInterval * 0.95. The result of 10001 * 0.95 is not an integer and this results in a Redis error "[ErrorReply: ERR value is not an integer or out of range]". 

I guess the simplest solution is to round it to integer before calling Redis. Or at least document this limitation or check the values during the app start up. 

Thanks

**Comment by soccermax** [comment]
Thanks for reporting this. Before tackling what you describe, one questions:
Did you configure your event with: `checkForNextChunk`? Because for fast processing of events, it should not be needed to increase the `runInterval`. The `runInterval` is for checking for failed events or after the starting of an instance.

To increase the throughput of events to be processed in the same instance you can use the event parameter: `parallelEventProcessing`.

For the issue you reported: I'll look into that, thanks for reproting

**Comment by mvoros** [comment]
When I was writing this bug, I had the mispelled parameter checkForNextChunk so it did not work. I now have both parallelEventProcessing and checkForNextChunk enabled and it now has much higher throughput. I still need to do more load testing to figure out where the bottlenecks are. Thanks for the tips.

Still, rounding the value for this parameter would be nice.

**Comment by soccermax** [comment]
Yes I'll provide a fix right a way. Thanks for the detailed investigation. Makes it easy to fix ;)

**Comment by soccermax** [comment]
fix is attached - I plan to release a new version next week
