### ISSUE TITLE
How to make CDS CQL calls inside event handler?

### ISSUE THREAD

**Issue by js1972** [cap-js-community/event-queue#74]
I am testing this package with use-case as follows:

I have a CAP application that displays entities relating to customers. The customers are stored in a remote system and for performance reasons we want to cache them locally instead of performing a remote call for every single record.

To do this I want to use a periodic event. In the handler I will make remote calls to read the customer list (delta) and update my locals tables with it.

So ideally I'd want the entire process to run in a transaction so that other online users are not affected by the updates until they are committed. So I am assuming I use the rollback strategy for this? Or are we supposed to set the completion status?

What is the best practice way to make CAP CQL calls ti write entries to the db given the event handler is provided with this parameter: `processContext`?

**Comment by soccermax** [comment]
Nice use cases, and it's a good idea to handle the fetching of data asynchronously using the event-queue. 

You wouldn't want to use the rollback strategy because with this transaction mode, all data written in the event-handler would always be rolled back. As a result, your local tables would not be updated at all. There's no need to specify a transaction mode for your use case. It would default to `isolated` by default. Here's an example how to interact with the DB.

```js
  async processPeriodicEvent(processContext, key, queueEntry) {
    const customerData = await fetchCustomerData();

    // Option 1
    await INSERT.into("table").entries(customerData);

    // Option 2
    const tx = this.getTxForEventProcessing(key);
    await tx.run(INSERT.into("table").entries(customerData));

    // Option 3
    const tx2 = cds.tx(processContext);
    await tx2.run(INSERT.into("table").entries(customerData));
    
    tx === tx2 // true
  }
```

If you want the data written with the event-handler to be rolled back, you can register the rollback.

```js
  async processPeriodicEvent(processContext, key, queueEntry) {
    const customerData = await fetchCustomerData();
    try {
      await INSERT.into("table").entries(customerData);
    } catch (err) {
      this.logger("Something went wrong", err);
      this.setShouldRollbackTransaction(key);
    }
  }
```

A transaction is also rolled back if an exception occurs that is caught by your event handler.

Does this answer your question?

**Comment by js1972** [comment]
Thankyou for that info - definitely helps. 
The three cql examples you gave each work with a transaction differently. Is there actually any difference between them?

**Comment by soccermax** [comment]
All three examples use the exact same CDS transaction object reference. Option 1 and 2 should also be defined in the CAP documentation. Option 3 is event-queue specific.

**Comment by soccermax** [comment]
The header available in CAP HTTP handlers is the auth token of the incoming request. As the event-queue invocation is not a HTTP-Req there is no auth header available.
However you can fetch a JWT token based on the XSUAA binding information. You can do the request to the XSUAA by your self or you use packages like `xssec` or `SAP Cloud SDK`. 
- xssec: `xssec.requests.requestClientCredentialsToken`
- [Cloud SDK](https://sap.github.io/cloud-sdk/api/v3/functions/sap_cloud_sdk_connectivity.getClientCredentialsToken.html)

**Comment by js1972** [comment]
@soccermax thanks for the heads up on that. Not only is there no user request context in an event handler but the security mechansim I was using to call the remote was relying on identity propagation. Switch to client credentials flow and this works now.
But... 
I am just using axios to get the token. When I look at the xssec doco (on npm) it does not reference the method: xssec.requests.requestClientCredentialsToken() so thinking its best not to use.

Oh and I also wasted about 6 hours because I had an extra ":" character in the Authorisation value after 'Bearer'. You've got to love programming - taking years off my life.  ;-)

**Comment by soccermax** [comment]
Glad that you solved this! 👍 Oh yeah, programming has its ups and downs, especially those incredibly small things that take hours to find. 😅
