### ISSUE TITLE
Question: Query on deleteFinishedEventsAfterDays config parameter?

### ISSUE THREAD

**Issue by js1972** [cap-js-community/event-queue#80]
I see the parameter `deleteFinishedEventsAfterDays ` default to 0 which means events are never deleted. When or why would you do this?
If I want a repeating periodic event then the events in the table can be deleted immediately after a successful transaction. Maybe you would leave it at 5 days to assist with debugging future issues.
Is there a reason why it would default to 0 or why we should leave it at 0?

**Comment by soccermax** [comment]
I'm currently working on version 1.0.0. With that, the default will be changed to 7 days. I started with 0 (never) to not introduce an incompatible change in a minor version.

**Comment by js1972** [comment]
Good to know. I'll set it to 7 for the time being.

**Comment by soccermax** [comment]
PR for the refactoring of this: https://github.com/cap-js-community/event-queue/pull/77
Just FYI
